import {
  collection,
  addDoc,
  updateDoc,
  deleteDoc,
  doc,
  query,
  where,
  getDocs,
  Timestamp,
} from 'firebase/firestore';
import { db } from '../firebase';
import { Income } from '../types';

type RecurringFrequency = 'weekly' | 'monthly' | 'yearly';

const toStartOfDay = (date: Date) => {
  const normalized = new Date(date);
  normalized.setHours(0, 0, 0, 0);
  return normalized;
};

const addByFrequency = (date: Date, frequency: RecurringFrequency) => {
  const next = new Date(date);
  if (frequency === 'weekly') {
    next.setDate(next.getDate() + 7);
    return next;
  }
  if (frequency === 'monthly') {
    next.setMonth(next.getMonth() + 1);
    return next;
  }
  next.setFullYear(next.getFullYear() + 1);
  return next;
};

export const addIncome = async (userId: string, data: Omit<Income, 'id' | 'createdAt'>) => {
  try {
    const incomeDate = new Date(data.date);
    // Strip undefined fields — Firestore rejects them
    const payload: Record<string, any> = {
      userId,
      amount: data.amount,
      source: data.source,
      description: data.description,
      date: Timestamp.fromDate(incomeDate),
      createdAt: Timestamp.now(),
    };
    if (data.isRecurring) {
      payload.isRecurring = true;
      payload.recurringFrequency = data.recurringFrequency ?? 'monthly';
      payload.recurringNextDate = Timestamp.fromDate(addByFrequency(incomeDate, payload.recurringFrequency));
      payload.lastAutoAdded = Timestamp.fromDate(incomeDate);
    }
    if (data.recurringParentId) payload.recurringParentId = data.recurringParentId;
    if (data.isAutoGenerated) payload.isAutoGenerated = data.isAutoGenerated;
    const docRef = await addDoc(collection(db, 'income'), payload);
    return docRef.id;
  } catch (error) {
    console.error('Error adding income:', error);
    throw error;
  }
};

export const getIncome = async (userId: string): Promise<Income[]> => {
  try {
    const q = query(
      collection(db, 'income'),
      where('userId', '==', userId),
    );
    const snapshot = await getDocs(q);
    return snapshot.docs
      .map((d) => ({
        id: d.id,
        ...d.data(),
        date: d.data().date.toDate(),
        createdAt: d.data().createdAt.toDate(),
        recurringNextDate: d.data().recurringNextDate?.toDate?.(),
        lastAutoAdded: d.data().lastAutoAdded?.toDate?.(),
      } as Income))
      .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  } catch (error) {
    console.error('Error getting income:', error);
    throw error;
  }
};

export const getMonthlyIncome = async (userId: string, month: string): Promise<number> => {
  try {
    const [year, monthNum] = month.split('-');
    const y = parseInt(year);
    const m = parseInt(monthNum) - 1;

    const all = await getIncome(userId);
    return all
      .filter((i) => {
        const d = new Date(i.date);
        return d.getFullYear() === y && d.getMonth() === m;
      })
      .reduce((sum, i) => sum + i.amount, 0);
  } catch (error) {
    console.error('Error getting monthly income:', error);
    throw error;
  }
};

export const deleteIncome = async (incomeId: string) => {
  try {
    await deleteDoc(doc(db, 'income', incomeId));
  } catch (error) {
    console.error('Error deleting income:', error);
    throw error;
  }
};

export const updateIncome = async (incomeId: string, updates: Partial<Income>) => {
  try {
    const ref = doc(db, 'income', incomeId);
    const updateData: any = { ...updates };
    if (updates.date) {
      updateData.date = Timestamp.fromDate(new Date(updates.date));
    }
    if (updates.recurringNextDate) {
      updateData.recurringNextDate = Timestamp.fromDate(new Date(updates.recurringNextDate));
    }
    if (updates.lastAutoAdded) {
      updateData.lastAutoAdded = Timestamp.fromDate(new Date(updates.lastAutoAdded));
    }
    await updateDoc(ref, updateData);
  } catch (error) {
    console.error('Error updating income:', error);
    throw error;
  }
};

/**
 * Auto-adds due entries for recurring income templates.
 * Returns the number of entries added during this run.
 */
export const processRecurringIncomeDue = async (userId: string): Promise<number> => {
  const recurringQuery = query(
    collection(db, 'income'),
    where('userId', '==', userId),
    where('isRecurring', '==', true),
  );

  const recurringSnapshot = await getDocs(recurringQuery);
  const today = toStartOfDay(new Date());
  let addedCount = 0;

  for (const recurringDoc of recurringSnapshot.docs) {
    const data = recurringDoc.data();
    const template = {
      id: recurringDoc.id,
      amount: data.amount,
      source: data.source,
      description: data.description,
      date: data.date?.toDate?.() as Date,
      recurringFrequency: (data.recurringFrequency ?? 'monthly') as RecurringFrequency,
      recurringNextDate: data.recurringNextDate?.toDate?.() as Date | undefined,
    };

    if (!template.date || !template.amount || !template.source || !template.description) {
      continue;
    }

    let nextDate = template.recurringNextDate ?? addByFrequency(template.date, template.recurringFrequency);
    let lastAutoAdded: Date | null = null;

    while (toStartOfDay(nextDate).getTime() <= today.getTime()) {
      await addDoc(collection(db, 'income'), {
        userId,
        amount: template.amount,
        source: template.source,
        description: template.description,
        date: Timestamp.fromDate(new Date(nextDate)),
        createdAt: Timestamp.now(),
        isRecurring: false,
        isAutoGenerated: true,
        recurringParentId: template.id,
      });

      addedCount += 1;
      lastAutoAdded = new Date(nextDate);
      nextDate = addByFrequency(nextDate, template.recurringFrequency);
    }

    if (lastAutoAdded) {
      await updateDoc(doc(db, 'income', template.id), {
        recurringNextDate: Timestamp.fromDate(nextDate),
        lastAutoAdded: Timestamp.fromDate(lastAutoAdded),
      });
    }
  }

  return addedCount;
};
